/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.luyi.umusic.web.action;

import java.net.InetAddress;
import java.net.UnknownHostException;
import java.text.SimpleDateFormat;
import java.util.Iterator;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.luyi.umusic.model.Admin;
import com.luyi.umusic.model.UserInfo;
import com.luyi.umusic.service.impl.UMusicManagerImpl;
import com.luyi.umusic.web.AdminForm;
import com.luyi.umusic.web.UserForm;

/** 
 * MyEclipse Struts
 * Creation date: 12-09-2013
 * 
 * XDoclet definition:
 * @struts.action path="/shareM" name="shareMForm" input="/form/shareM.jsp" scope="request" validate="true"
 * @struts.action-forward name="fail" path="/share.jsp"
 * @struts.action-forward name="MusicLib" path="/musiclib.jsp"
 */
public class AdminAction extends DispatchAction {
	/*
	 * Generated Methods
	 */
	UMusicManagerImpl uMusicManagerImpl;
	
	public UMusicManagerImpl getUMusicManagerImpl()
	{
		return uMusicManagerImpl;
	}
	
	public void setUMusicManagerImpl(UMusicManagerImpl uMusicManagerImpl)
	{
		this.uMusicManagerImpl = uMusicManagerImpl;
	}
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward login(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AdminForm adminForm = (AdminForm) form;// TODO Auto-generated method stub
		Admin a = new Admin(adminForm.getAdminname(), adminForm.getAdminpwd());
		
		if(uMusicManagerImpl.admin(a))
		{	
			request.getSession().setAttribute("adminName", adminForm.getAdminname());
			request.getSession().setAttribute("adminPwd", adminForm.getAdminpwd());
			request.getSession().setAttribute("adminId", a.getId().toString());
			
			return mapping.findForward("umusic.admin");
		}
		else
		{
			adminForm.setAdminpwd("");
			return mapping.findForward("umusic.adminlogin");
		}
	}
	
	public ActionForward all(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		List adminlist = uMusicManagerImpl.findAllAdmin();
		request.getSession().setAttribute("adminlist", adminlist);
		return mapping.findForward("umusic.admininfo");
	}
}