/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.luyi.umusic.web.action;

import java.text.SimpleDateFormat;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.luyi.umusic.model.Feedback;
import com.luyi.umusic.model.Music;
import com.luyi.umusic.service.impl.UMusicManagerImpl;
import com.luyi.umusic.web.FeedbackForm;

/** 
 * MyEclipse Struts
 * Creation date: 12-09-2013
 * 
 * XDoclet definition:
 * @struts.action path="/shareM" name="shareMForm" input="/form/shareM.jsp" scope="request" validate="true"
 * @struts.action-forward name="fail" path="/share.jsp"
 * @struts.action-forward name="MusicLib" path="/musiclib.jsp"
 */
public class FeedbackAction extends DispatchAction {
	/*
	 * Generated Methods
	 */
	UMusicManagerImpl uMusicManagerImpl;
	
	public UMusicManagerImpl getUMusicManagerImpl()
	{
		return uMusicManagerImpl;
	}
	
	public void setUMusicManagerImpl(UMusicManagerImpl uMusicManagerImpl)
	{
		this.uMusicManagerImpl = uMusicManagerImpl;
	}
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward save(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		FeedbackForm feedbackForm = (FeedbackForm) form;// TODO Auto-generated method stub
		int id = Integer.parseInt(request.getParameter("musicId"));
		SimpleDateFormat sdf = new SimpleDateFormat("MM-dd hh:mm");  
		String date = sdf.format(new java.util.Date()); 
		
		Feedback f = new Feedback();
		f.setUserName(request.getSession().getAttribute("userName").toString());
		f.setContent(feedbackForm.getContent());
		f.setPubTime(date);
		f.setMusicId(id);
		
		if(uMusicManagerImpl.saveFeedback(f))
		{
			feedbackForm.setContent("");
			return all(mapping, form, request, response);
		}
		else
		{
			return mapping.findForward("umusic.home");
		}
	}
	
	public ActionForward delete(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		int id = Integer.parseInt(request.getParameter("feedbackId"));
		uMusicManagerImpl.deleteF(id);
		return all(mapping, form, request, response);
	}
	
	public ActionForward all(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		List feedbacklist = uMusicManagerImpl.findAllFeedback();
		request.getSession().setAttribute("feedbacklist", feedbacklist);
		return mapping.findForward("umusic.home");
	}
}