/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.luyi.umusic.web;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 12-19-2013
 * 
 * XDoclet definition:
 * @struts.form name="adminForm"
 */
public class AdminForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** adminname property */
	private String adminname;

	/** adminpwd property */
	private String adminpwd;

	/** lastip property */
	private String lastip;

	/** lastdate property */
	private String lastdate;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the adminname.
	 * @return String
	 */
	public String getAdminname() {
		return adminname;
	}

	/** 
	 * Set the adminname.
	 * @param adminname The adminname to set
	 */
	public void setAdminname(String adminname) {
		this.adminname = adminname;
	}

	/** 
	 * Returns the adminpwd.
	 * @return String
	 */
	public String getAdminpwd() {
		return adminpwd;
	}

	/** 
	 * Set the adminpwd.
	 * @param adminpwd The adminpwd to set
	 */
	public void setAdminpwd(String adminpwd) {
		this.adminpwd = adminpwd;
	}

	/** 
	 * Returns the lastip.
	 * @return String
	 */
	public String getLastip() {
		return lastip;
	}

	/** 
	 * Set the lastip.
	 * @param lastip The lastip to set
	 */
	public void setLastip(String lastip) {
		this.lastip = lastip;
	}

	/** 
	 * Returns the lastdate.
	 * @return String
	 */
	public String getLastdate() {
		return lastdate;
	}

	/** 
	 * Set the lastdate.
	 * @param lastdate The lastdate to set
	 */
	public void setLastdate(String lastdate) {
		this.lastdate = lastdate;
	}
}