/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.luyi.umusic.web;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 12-18-2013
 * 
 * XDoclet definition:
 * @struts.form name="feedbackForm"
 */
public class FeedbackForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** pubtime property */
	private String pubtime;

	/** content property */
	private String content;

	/** username property */
	private String username;

	/** musicid property */
	private String musicid;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the pubtime.
	 * @return String
	 */
	public String getPubtime() {
		return pubtime;
	}

	/** 
	 * Set the pubtime.
	 * @param pubtime The pubtime to set
	 */
	public void setPubtime(String pubtime) {
		this.pubtime = pubtime;
	}

	/** 
	 * Returns the content.
	 * @return String
	 */
	public String getContent() {
		return content;
	}

	/** 
	 * Set the content.
	 * @param content The content to set
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/** 
	 * Returns the username.
	 * @return String
	 */
	public String getUsername() {
		return username;
	}

	/** 
	 * Set the username.
	 * @param username The username to set
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/** 
	 * Returns the musicid.
	 * @return String
	 */
	public String getMusicid() {
		return musicid;
	}

	/** 
	 * Set the musicid.
	 * @param musicid The musicid to set
	 */
	public void setMusicid(String musicid) {
		this.musicid = musicid;
	}
}