/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.luyi.umusic.web;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 12-12-2013
 * 
 * XDoclet definition:
 * @struts.form name="sharePForm"
 */
public class SharePForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** photoTitle property */
	private String photoTitle;

	/** photoInfo property */
	private String photoInfo;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the photoTitle.
	 * @return String
	 */
	public String getPhotoTitle() {
		return photoTitle;
	}

	/** 
	 * Set the photoTitle.
	 * @param photoTitle The photoTitle to set
	 */
	public void setPhotoTitle(String photoTitle) {
		this.photoTitle = photoTitle;
	}

	/** 
	 * Returns the photoInfo.
	 * @return String
	 */
	public String getPhotoInfo() {
		return photoInfo;
	}

	/** 
	 * Set the photoInfo.
	 * @param photoInfo The photoInfo to set
	 */
	public void setPhotoInfo(String photoInfo) {
		this.photoInfo = photoInfo;
	}
}