/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.luyi.umusic.web;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 12-09-2013
 * 
 * XDoclet definition:
 * @struts.form name="shareMForm"
 */
public class ShareMForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** musicType property */
	private String musicType;

	/** musicName property */
	private String musicTitle;

	/** musicDcpt property */
	private String musicDcpt;
	
	private String singer;

	private String sourch;
	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the musicType.
	 * @return String
	 */
	public String getMusicType() {
		return musicType;
	}

	/** 
	 * Set the musicType.
	 * @param musicType The musicType to set
	 */
	public void setMusicType(String musicType) {
		this.musicType = musicType;
	}
	
	public String getSourch() {
		return sourch;
	}

	/** 
	 * Set the musicType.
	 * @param musicType The musicType to set
	 */
	public void setSourch(String sourch) {
		this.sourch = sourch;
	}

	/** 
	 * Returns the musicTitle.
	 * @return String
	 */
	public String getmusicTitle() {
		return musicTitle;
	}

	/** 
	 * Set the musicTitle.
	 * @param musicTitle The musicTitle to set
	 */
	public void setmusicTitle(String musicTitle) {
		this.musicTitle = musicTitle;
	}

	/** 
	 * Returns the musicDcpt.
	 * @return String
	 */
	public String getMusicDcpt() {
		return musicDcpt;
	}

	/** 
	 * Set the musicDcpt.
	 * @param musicDcpt The musicDcpt to set
	 */
	public void setMusicDcpt(String musicDcpt) {
		this.musicDcpt = musicDcpt;
	}
	
	public String getSinger() {
		return singer;
	}

	/** 
	 * Set the musicDcpt.
	 * @param musicDcpt The musicDcpt to set
	 */
	public void setSinger(String singer) {
		this.singer = singer;
	}
}